
### LOGIN - retorna o access_token para usar nas rotas autenticadas
POST https://cduaqnxixtfsijstimxb.supabase.co/auth/v1/token?grant_type=password
Content-Type: application/json
apikey: sb_publishable_S7qnVDQzddBDaRvEp3g5Rw_uwzvsLYB

{
  "email": "murilobalves1@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3333/api/users
Content-Type: application/json

{
  "name": "Vanessa",
  "email": "vanessa@email.com",
  "password": "123456"
}

###
GET  http://localhost:3333/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY4N2NlNzYzLWQ1NDctNDZmNy1iM2Q0LTIxY2RhNzEzNzAwMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NkdWFxbnhpeHRmc2lqc3RpbXhiLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlN2Y1ZmU5MC04ZjVhLTQ1MzEtOTE2OC0zODdiYTQwNjFhMWUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxOTY2NzExLCJpYXQiOjE3ODE5NjMxMTEsImVtYWlsIjoibXVyaWxvYmFsdmVzMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MTk2MzExMX1dLCJzZXNzaW9uX2lkIjoiMGUyYWU5ODUtMGVhNS00ZWZlLWE5OTMtMzM0OTAxZjE0OTIxIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.dj0iAkH6q1q25bnd-UITsrifeaJrrpfyciHEBkp5FuB0hZ89PSwLMOe_Y6UU9aMEfMLszG8OxYl9N5zkWlc_Jw

###
POST http://localhost:3333/api/users
Content-Type: application/json

{
  "name": "Murilo",
  "email": "murilo@email.com",
  "password": "123456"
}

###
PATCH http://localhost:3333/api/users/c8c038f4-e349-4698-8a52-b8d2cd0d549b
Content-Type: application/json

{
  "name": "Murilo b",
  "phone": 44998909877,
  "city": "Santos",
  "zipCode": "01001000",
  "street": "Rua das Flores",
  "number": "123",
  "district": "Centro",
  "city": "São Paulo",
  "state": "SP"
}


###
GET  http://localhost:3333/api/bakery
Content-Type: application/json

###
POST http://localhost:3333/api/bakery
Content-Type: application/json

{
  "name": "Padaria Central",
  "cnpj": "12345678000199",
  "email": "padaria@email.com",
  "phone": "11999999999",
  "whatsapp": "11999999999",
  "serviceStartAt": "08:00",
  "serviceEndAt": "18:00"
}


###
POST http://localhost:3333/api/subscribe
Content-Type: application/json

{
  "userId": "99afc466-c437-439d-9a8d-489fba62cf34",
  "bakeryId": "e0758e45-fd77-4dfc-86ad-dab31b7932ed",
  "subscribe": {
    "serviceStartAt": "01-05-2026",
    "serviceEndAt": "30-05-2026",
    "deliveryStartAt": "8:00",
    "deliveryEndAt": "9:00",
    "notes": "2 paes",
    "frequency": "weekly",
    "daysWeek": ["monday", "friday"]
  }
}

###
POST http://localhost:3333/api/subscribe
Content-Type: application/json

{
  "userId": "99afc466-c437-439d-9a8d-489fba62cf34",
  "bakeryId": "e0758e45-fd77-4dfc-86ad-dab31b7932ed",
  "subscribe": {
    "serviceStartAt": "16-06-2026",
    "serviceEndAt": "29-06-2026",
    "deliveryStartAt": "8:00",
    "deliveryEndAt": "9:00",
    "notes": "10 paes",
    "frequency": "daily"
  }
}


###
GET http://localhost:3333/api/subscribe/99afc466-c437-439d-9a8d-489fba62cf34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY4N2NlNzYzLWQ1NDctNDZmNy1iM2Q0LTIxY2RhNzEzNzAwMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NkdWFxbnhpeHRmc2lqc3RpbXhiLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlN2Y1ZmU5MC04ZjVhLTQ1MzEtOTE2OC0zODdiYTQwNjFhMWUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxOTY2NzExLCJpYXQiOjE3ODE5NjMxMTEsImVtYWlsIjoibXVyaWxvYmFsdmVzMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MTk2MzExMX1dLCJzZXNzaW9uX2lkIjoiMGUyYWU5ODUtMGVhNS00ZWZlLWE5OTMtMzM0OTAxZjE0OTIxIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.dj0iAkH6q1q25bnd-UITsrifeaJrrpfyciHEBkp5FuB0hZ89PSwLMOe_Y6UU9aMEfMLszG8OxYl9N5zkWlc_Jw

###
GET http://localhost:3333/api/subscribe
Content-Type: application/json

###
GET http://localhost:3333/api/subscribe?serviceDate=2026-06-03
Content-Type: application/json

####
GET http://localhost:3333/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjY4N2NlNzYzLWQ1NDctNDZmNy1iM2Q0LTIxY2RhNzEzNzAwMCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2NkdWFxbnhpeHRmc2lqc3RpbXhiLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJlN2Y1ZmU5MC04ZjVhLTQ1MzEtOTE2OC0zODdiYTQwNjFhMWUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgxODI0MjY0LCJpYXQiOjE3ODE4MjA2NjQsImVtYWlsIjoibXVyaWxvYmFsdmVzMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4MTgyMDY2NH1dLCJzZXNzaW9uX2lkIjoiZjgxNDhiNzYtNzIyYy00Mjg5LTg1YjQtMzI3YTE5ZDc2ZGNkIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.e9LEv_y_2GPg7QNnO6xTTVIiZ957zCau_paRN2UhRRdizaXDr0dc7gNHhCIOgv1iRx1zXfHstZh02mf5AOXg1A

####
PATCH  http://localhost:3333/api/orders/12421/28eb82e8-4d06-4ca7-977b-0caed0a32cbe
Content-Type: application/json
Authorization: Bearer SEU_TOKEN_AQUI

{
  "status": "PICKED_UP"
}

####
POST  http://localhost:3333/api/delivery/register
Content-Type: application/json

{
  "name": "Aragorn",
  "document": "55566644489",
  "phone": "44999885566",
  "email": "aragorn@email.com",
  "modal": "MOTORCYCLE"
}
