
###
POST http://localhost:3333/api/users
Content-Type: application/json

{
  "name": "Vanessa",
  "email": "vanessa@email.com",
  "password": "123456"
}

###
GET  http://localhost:3333/api/users
Content-Type: application/json

