
###
POST http://localhost:3333/api/users
Content-Type: application/json

{
  "name": "Vanessa",
  "email": "vanessa@email.com",
  "password": "123456"
}

###
GET  http://localhost:3333/api/users
Content-Type: application/json

###
POST http://localhost:3333/api/users
Content-Type: application/json

{
  "name": "Vanessa",
  "email": "vanessa@email.com",
  "password": "123456"
}

###
PATCH http://localhost:3333/api/users/c8c038f4-e349-4698-8a52-b8d2cd0d549b
Content-Type: application/json

{
  "name": "Murilo b",
  "phone": 44998909877,
  "city": "Santos",
  "zipCode": "01001000",
  "street": "Rua das Flores",
  "number": "123",
  "district": "Centro",
  "city": "São Paulo",
  "state": "SP"
}


==============================================
Bakery
==============================================

###
GET  http://localhost:3333/api/bakery
Content-Type: application/json

###
POST http://localhost:3333/api/bakery
Content-Type: application/json

{
  "name": "Padaria Central",
  "cnpj": "12345678000199",
  "email": "padaria@email.com",
  "phone": "11999999999",
  "whatsapp": "11999999999",
  "serviceStartAt": "08:00",
  "serviceEndAt": "18:00"
}

==============================================
Subscribe
==============================================

###
POST http://localhost:3333/api/subscribe
Content-Type: application/json

{
  "userId": "bd910059-c841-4cfa-ba95-206597ab384c",
  "bakeryId": "f3b5a586-5783-4333-a6b6-f5471344687e",
  "subscribe": {
    "start": "8:00",
    "end": "8:30",
    "notes": "10 paes" 
  }
}